name: moviroo
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/ls2.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "images/ls2.png"

flutter_native_splash:
  color: "#ffffff"
  image: images/logo6.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFit
  fullscreen: true
  android_12:
    color: "#ffffff"
    image: images/logo6.png

flutter:
  uses-material-design: true
  assets:
    - images/logo6.png