name: moviroo
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  video_player: ^2.9.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  easy_localization: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/image.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "images/image.png"

flutter_native_splash:
  color: "#ffffff"
  image: images/logo6.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFit
  fullscreen: true
  android_12:
    color: "#ffffff"
    image: images/logo6.png

flutter:
  uses-material-design: true
  generate: true
  assets:
    - images/logo6.png
    - images/google.png
    - images/apple.png
    - images/ls.png
    - images/splash.mov
    - images/remake.mp4
    - images/remake.gif
    - images/lsnn.png
    - images/logo.gif
    - images/complete.gif
    - images/logob.png
    - images/translations/en.json
    - images/translations/fr.json
    - images/translations/ar.json
    - images/image.png
    - images/flags/usa.png
    - images/flags/france.png
    - images/flags/saudi.png

